name: Testing_workflow

on: 
  push:
    branches:
      main
  pull_request:
    branches:
      main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - name : Print
      run : |
        echo "Hello World"
        echo "This my first yaml workflow script"
        echo "Workflow: $GITHUB_WORKFLOW"
        echo "Repository: $GITHUB_REPOSITORY"
        echo "Branch: ${GITHUB_REF#refs/heads/}"
        echo "Commit: $GITHUB_SHA"
        echo "Actor: $GITHUB_ACTOR"
        echo "Event: $GITHUB_EVENT_NAME"
        echo "Runner OS: $RUNNER_OS"
    - name : print_env
      run : |
        echo "This is second step"
